"""empty message

Revision ID: 446dcbc51268
Revises: 486bf03989f3
Create Date: 2016-05-14 14:44:09.616598

"""

# revision identifiers, used by Alembic.
revision = '446dcbc51268'
down_revision = '486bf03989f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street0', sa.Text(), nullable=False),
    sa.Column('street1', sa.Text(), nullable=False),
    sa.Column('street2', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('province', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table('user_address',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_address')
    op.drop_table('address')
    ### end Alembic commands ###
